image: 'maven:3.3.9-jdk-8'
stages:
  - test
  - build
services:
  - 'mysql:latest'
  - 'mongo:latest'
variables:
  MYSQL_DATABASENAME: "userDb"
  MYSQL_URL: "jdbc:mysql://mysql/userDb?createDatabaseIfNotExist=true"
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "password"
  MYSQL_ROOT_PASSWORD: "root"
  MONGO_DATABASENAME: "SBA_PROG"
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
cache:
  paths:
    - .m2/repository
    -  target
maven-test:
  stage: test
  script: "echo No exeuction of Test"
#  script: "mvn test"
maven-build:
  stage: build
  script: "mvn clean compile"
  artifacts:
    paths:
      - target/*.jar